### PR TITLE
Update Linux patches to apply correctly and use Xen 4.13

### PR DESCRIPTION
**Pull request by tklengyel**
Also install openssh by default

### CODE REVIEW

**Comment by stewdk** [comment]
Unfortunately, installing openssh server in this way will generate keys during the build.

    Creating SSH2 RSA key; this may take some time ...
    2048 SHA256:8n2VBKP/OCkBrWU1hBWlp0Exs+f/EbMUGjsyidusLhA root@ubuntu (RSA)
    Creating SSH2 ECDSA key; this may take some time ...
    256 SHA256:zxkLydK0gIgKrlCeeJQ8Wnu8KHMSkI3FTHXews1B/dM root@ubuntu (ECDSA)
    Creating SSH2 ED25519 key; this may take some time ...
    256 SHA256:dqqe4rumnreiEQrMfCRN0NGeEGZd+nx+VGJhVRGYjDU root@ubuntu (ED25519)

I would prefer those keys be generated during first boot. I would be happy to accept everything else in this pull request.
Can you re-submit the patch without the ssh install step please?
Also, if you find a way to install ssh without generating keys at build time (and instead generate them during first boot), I'd be happy to accept that as well, but preferably in a separate patch.

**Comment by tklengyel** [comment]
How about adding something like https://gist.github.com/Ham5ter/6cf693f67a1792b55f294969647a4e6a?

**Comment by stewdk** [comment]
> How about adding something like https://gist.github.com/Ham5ter/6cf693f67a1792b55f294969647a4e6a?

This seems like a good approach.

**Comment by tklengyel** [comment]
Now if we could only get WiFi working this would be perfect ;)

**Comment by stewdk** [comment]
I sent a message to the author of the script regenerate_ssh_host_keys_init.sh asking to add an open source license.

**Comment by tklengyel** [comment]
Could also use https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/debian/raspberrypi-sys-mods.regenerate_ssh_host_keys.service

**Comment by stewdk** [comment]
Yes, I prefer that. It's BSD 3-Clause. https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/debian/copyright

**Pull request merged**
